### ISSUE TITLE
Add grumphp parameters to drupal conventions.

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/code-review#77]
Currently most projects need grumphp configuration like this:

```
imports:
  - { resource: vendor/openeuropa/code-review/dist/drupal-conventions.yml }
parameters:
  tasks.phpcs.ignore_patterns:
    - build/
    - node_modules/
    - vendor/
  tasks.phpcs.triggered_by:
    - inc
    - install
    - module
    - php
    - theme
    - yml
```
Since these parameters are common in most projects, they can be added to code-review's drupal conventions.
